development:
  adapter: postgresql
  database: angular_auth_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: angular_auth_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: angular_auth_prod
  pool: 5
  timeout: 5000