# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c67055d3a17aa505f07935ce85cb0043d5e70b03c52499f3ba6d9bd1d91eae777c41350ce1130256af31a8bc354c0d78db6667269b0b2c67f0bee4b267f3471

test:
  secret_key_base: f2217e61071c058a80d26cba7d57337dd2be7bf8c5ff1dbbe20ea0799f83125e2d88fb5def5fa8741b200a64a1b25f0fa1ef66542d1a04db204705715550e591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
